//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/23/2017 4:45:21 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace VendingMachineApp.Models
{
    public partial class Machine {

        public Machine()
        {
            this.ProductMachines = new List<ProductMachine>();
            OnCreated();
        }

        public virtual int MachineId
        {
            get;
            set;
        }

        public virtual string MachineName
        {
            get;
            set;
        }

        public virtual string MachineAddress
        {
            get;
            set;
        }

        public virtual string MachineManufacturer
        {
            get;
            set;
        }

        public virtual string MachineModel
        {
            get;
            set;
        }

        public virtual string MachineType
        {
            get;
            set;
        }

        public virtual string MachineDimension
        {
            get;
            set;
        }

        public virtual string MachineVoltage
        {
            get;
            set;
        }

        public virtual short OwnerId
        {
            get;
            set;
        }

        public virtual IList<ProductMachine> ProductMachines
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
