//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/23/2017 4:45:21 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace VendingMachineApp.Models
{
    public partial class Product {

        public Product()
        {
            this.ProductMachines = new List<ProductMachine>();
            OnCreated();
        }

        public virtual int ProductId
        {
            get;
            set;
        }

        public virtual string ProductName
        {
            get;
            set;
        }

        public virtual string ProductType
        {
            get;
            set;
        }

        public virtual string ProductImage
        {
            get;
            set;
        }

        public virtual IList<ProductMachine> ProductMachines
        {
            get;
            set;
        }
    
        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
