//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 4/23/2017 4:45:21 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------


namespace VendingMachineApp.Models
{
    public partial class ProductMachine {

        public ProductMachine()
        {
            //this.ProductOrders = new List<ProductOrder>();
            //this.Supplies = new List<Supply>();
            OnCreated();
        }

        public virtual int ProductMachineId
        {
            get;
            set;
        }

        public virtual int ProductMachineQty
        {
            get;
            set;
        }

        public virtual int ProductMachineIndex
        {
            get;
            set;
        }

        public virtual int ProductId
        {
            get;
            set;
        }

        public virtual int MachineId
        {
            get;
            set;
        }

        public virtual decimal ProductMachinePrice
        {
            get;
            set;
        }

        public virtual Product Product
        {
            get;
            set;
        }

        public virtual Machine Machine
        {
            get;
            set;
        }
        //public virtual IList<ProductOrder> ProductOrders
        //{
        //    get;
        //    set;
        //}

        #region Extensibility Method Definitions

        partial void OnCreated();
        
        #endregion
    }

}
